win32: explicitly ignore CloseAdapter return value
The mingw build flags a warning about the ignored return type.
Since there's nothing we can do here, just mask it out:

.../va_win32.c:110:9: error: ignoring return value of function
declared with attribute 'warn_unused_result' [-Werror=unused-result]

Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>